<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Prepaid</name>
   <tag></tag>
   <elementGuidId>27480285-951e-46a2-acb4-28289e84cc42</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;_2Bze&quot;]/div[@class=&quot;_1N8k&quot;]/div[@class=&quot;_2527&quot;]/div[1]/div[@class=&quot;ngcx&quot;]/div[@class=&quot;_1NPY&quot;]/div[1]/div[@class=&quot;_1iju&quot;]/div[@class=&quot;wt_a&quot;]/label[@class=&quot;_1oun&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>156</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prepaid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1oun</value>
   </webElementProperties>
</WebElementEntity>
