<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul</name>
   <tag></tag>
   <elementGuidId>54efffd6-9ccf-46fa-8189-084a583a220e</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;_2Bze&quot;]/div[@class=&quot;_1N8k&quot;]/div[@class=&quot;_2527&quot;]/div[1]/div[@class=&quot;ngcx&quot;]/div[@class=&quot;_1NPY&quot;]/div[1]/div[@class=&quot;_1PHd&quot;]/ul[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>166</value>
   </webElementProperties>
</WebElementEntity>
